# Default values for multicalchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
frontendReplicaCount: 2
backendReplicaCount: 3
dependencies:
  useRedis: no
  usePodRedis: yes
  redisSecret: rediscachesecret
  useAppInsights: no
  appInsightsSecretValue: 
  useIngress: no
image:
  repository: oestregistry.azurecr.io
  frontendImage: jsfrontend
  frontendTag: latest
  backendImage: jsbackend
  backendTag: latest
  pullPolicy: IfNotPresent
  pullSecret: kuberegistry
service:
  frontendType: LoadBalancer
  backendType: ClusterIP
  dnsName: calcName
resources:
  limits:
    cpu: 300m
    memory: 350Mi
  requests:
    cpu: 250m
    memory: 256Mi
